///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PreEmp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the PreEmpRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("9b05a258-7840-45e3-9df0-85c25bcfbfcc")]
    public partial class PreEmpRepository : RepoGenBaseFolder
    {
        static PreEmpRepository instance = new PreEmpRepository();
        PreEmpRepositoryFolders.CalculatorAppFolder _calculator;

        /// <summary>
        /// Gets the singleton class instance representing the PreEmpRepository element repository.
        /// </summary>
        [RepositoryFolder("9b05a258-7840-45e3-9df0-85c25bcfbfcc")]
        public static PreEmpRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public PreEmpRepository() 
            : base("PreEmpRepository", "/", null, 0, false, "9b05a258-7840-45e3-9df0-85c25bcfbfcc", ".\\RepositoryImages\\PreEmpRepository9b05a258.rximgres")
        {
            _calculator = new PreEmpRepositoryFolders.CalculatorAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("9b05a258-7840-45e3-9df0-85c25bcfbfcc")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Calculator folder.
        /// </summary>
        [RepositoryFolder("fd353da2-cb7b-4401-881b-7b3b6346f0e5")]
        public virtual PreEmpRepositoryFolders.CalculatorAppFolder Calculator
        {
            get { return _calculator; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class PreEmpRepositoryFolders
    {
        /// <summary>
        /// The CalculatorAppFolder folder.
        /// </summary>
        [RepositoryFolder("fd353da2-cb7b-4401-881b-7b3b6346f0e5")]
        public partial class CalculatorAppFolder : RepoGenBaseFolder
        {
            PreEmpRepositoryFolders.NumberPadFolder _numberpad;
            RepoItemInfo _squarerootbuttonInfo;
            RepoItemInfo _titlebarInfo;
            RepoItemInfo _text7Info;
            RepoItemInfo _multiplybuttonInfo;
            RepoItemInfo _text5Info;
            RepoItemInfo _equalbuttonInfo;
            RepoItemInfo _normaloutputInfo;
            RepoItemInfo _clearbuttonInfo;
            RepoItemInfo _sometextInfo;
            RepoItemInfo _iconInfo;
            RepoItemInfo _programmerInfo;
            RepoItemInfo _headerInfo;
            RepoItemInfo _maximizeInfo;
            RepoItemInfo _togglepanebuttonInfo;
            RepoItemInfo _standardInfo;
            RepoItemInfo _plusbuttonInfo;

            /// <summary>
            /// Creates a new Calculator  folder.
            /// </summary>
            public CalculatorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Calculator", "/winapp[@packagename='Microsoft.WindowsCalculator']", parentFolder, 30000, null, true, "fd353da2-cb7b-4401-881b-7b3b6346f0e5", "")
            {
                _numberpad = new PreEmpRepositoryFolders.NumberPadFolder(this);
                _squarerootbuttonInfo = new RepoItemInfo(this, "SquareRootButton", "?/?/container[@automationid='StandardFunctions']/button[@automationid='squareRootButton']", 30000, null, "7720469e-e607-4d49-8a26-ee84cdfe74ff");
                _titlebarInfo = new RepoItemInfo(this, "TitleBar", "titlebar[@name='Calculator' and @classname='ApplicationFrameTitleBarWindow']", 30000, null, "3c290383-741d-4bf3-8798-01b4f9ae2eee");
                _text7Info = new RepoItemInfo(this, "Text7", ".//button[@automationid='num7Button']/text[@name='7']", 30000, null, "8f6efca5-62aa-49ba-8dbc-a6bd6eb75fb3");
                _multiplybuttonInfo = new RepoItemInfo(this, "MultiplyButton", "?/?/container[@automationid='StandardOperators']/button[@automationid='multiplyButton']", 30000, null, "9be5f0d6-53ba-422f-a7dc-724f00788d7b");
                _text5Info = new RepoItemInfo(this, "Text5", ".//button[@automationid='num5Button']/text[@name='5']", 30000, null, "52725a3b-07c3-4894-801e-40f2c603b520");
                _equalbuttonInfo = new RepoItemInfo(this, "EqualButton", "?/?/container[@automationid='StandardOperators']/button[@automationid='equalButton']", 30000, null, "648bff43-e3c0-4688-8620-2fed87644e9a");
                _normaloutputInfo = new RepoItemInfo(this, "NormalOutput", "?/?/text[@automationid='CalculatorResults']/?/?/text[@automationid='NormalOutput']", 30000, null, "3ae99ce4-cc44-40a4-8180-b08713668233");
                _clearbuttonInfo = new RepoItemInfo(this, "ClearButton", "?/?/container[@automationid='DisplayControls']/button[@automationid='clearButton']", 30000, null, "edb8d9b7-853e-4b36-b973-6b634c181e19");
                _sometextInfo = new RepoItemInfo(this, "SomeText", ".//button[@automationid='plusButton']/text[@name='']", 30000, null, "36d7a303-6702-41aa-bca7-da878644ff65");
                _iconInfo = new RepoItemInfo(this, "Icon", "?/?/text[@automationid='Icon']", 30000, null, "12e21b71-7009-43ec-85d6-5caeb68ade14");
                _programmerInfo = new RepoItemInfo(this, "Programmer", "form[@automationid='PaneRoot']/?/?/listitem[@automationid='Programmer']", 30000, null, "ee916f84-b6af-4451-afe0-016fb874d28b");
                _headerInfo = new RepoItemInfo(this, "Header", "text[@automationid='Header']", 30000, null, "82ce8e8d-9011-4985-a2af-8f2a50d4075f");
                _maximizeInfo = new RepoItemInfo(this, "Maximize", "?/?/button[@automationid='Maximize']", 30000, null, "79318610-2086-4409-a16f-2674ab0c704b");
                _togglepanebuttonInfo = new RepoItemInfo(this, "TogglePaneButton", "button[@automationid='TogglePaneButton']", 30000, null, "882b82cd-d4ef-4cfa-b97e-74e9a96f3848");
                _standardInfo = new RepoItemInfo(this, "Standard", "form[@automationid='PaneRoot']/?/?/listitem[@automationid='Standard']", 30000, null, "49315fdc-49f8-44fc-839a-f26f2a1115f8");
                _plusbuttonInfo = new RepoItemInfo(this, "PlusButton", "?/?/container[@automationid='StandardOperators']/button[@automationid='plusButton']", 30000, null, "a9775261-69cd-4d1f-8bdd-1c00b6f0a2a1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fd353da2-cb7b-4401-881b-7b3b6346f0e5")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fd353da2-cb7b-4401-881b-7b3b6346f0e5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SquareRootButton item.
            /// </summary>
            [RepositoryItem("7720469e-e607-4d49-8a26-ee84cdfe74ff")]
            public virtual Ranorex.Button SquareRootButton
            {
                get
                {
                    return _squarerootbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SquareRootButton item info.
            /// </summary>
            [RepositoryItemInfo("7720469e-e607-4d49-8a26-ee84cdfe74ff")]
            public virtual RepoItemInfo SquareRootButtonInfo
            {
                get
                {
                    return _squarerootbuttonInfo;
                }
            }

            /// <summary>
            /// The TitleBar item.
            /// </summary>
            [RepositoryItem("3c290383-741d-4bf3-8798-01b4f9ae2eee")]
            public virtual Ranorex.TitleBar TitleBar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The TitleBar item info.
            /// </summary>
            [RepositoryItemInfo("3c290383-741d-4bf3-8798-01b4f9ae2eee")]
            public virtual RepoItemInfo TitleBarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }

            /// <summary>
            /// The Text7 item.
            /// </summary>
            [RepositoryItem("8f6efca5-62aa-49ba-8dbc-a6bd6eb75fb3")]
            public virtual Ranorex.Text Text7
            {
                get
                {
                    return _text7Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text7 item info.
            /// </summary>
            [RepositoryItemInfo("8f6efca5-62aa-49ba-8dbc-a6bd6eb75fb3")]
            public virtual RepoItemInfo Text7Info
            {
                get
                {
                    return _text7Info;
                }
            }

            /// <summary>
            /// The MultiplyButton item.
            /// </summary>
            [RepositoryItem("9be5f0d6-53ba-422f-a7dc-724f00788d7b")]
            public virtual Ranorex.Button MultiplyButton
            {
                get
                {
                    return _multiplybuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MultiplyButton item info.
            /// </summary>
            [RepositoryItemInfo("9be5f0d6-53ba-422f-a7dc-724f00788d7b")]
            public virtual RepoItemInfo MultiplyButtonInfo
            {
                get
                {
                    return _multiplybuttonInfo;
                }
            }

            /// <summary>
            /// The Text5 item.
            /// </summary>
            [RepositoryItem("52725a3b-07c3-4894-801e-40f2c603b520")]
            public virtual Ranorex.Text Text5
            {
                get
                {
                    return _text5Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text5 item info.
            /// </summary>
            [RepositoryItemInfo("52725a3b-07c3-4894-801e-40f2c603b520")]
            public virtual RepoItemInfo Text5Info
            {
                get
                {
                    return _text5Info;
                }
            }

            /// <summary>
            /// The EqualButton item.
            /// </summary>
            [RepositoryItem("648bff43-e3c0-4688-8620-2fed87644e9a")]
            public virtual Ranorex.Button EqualButton
            {
                get
                {
                    return _equalbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EqualButton item info.
            /// </summary>
            [RepositoryItemInfo("648bff43-e3c0-4688-8620-2fed87644e9a")]
            public virtual RepoItemInfo EqualButtonInfo
            {
                get
                {
                    return _equalbuttonInfo;
                }
            }

            /// <summary>
            /// The NormalOutput item.
            /// </summary>
            [RepositoryItem("3ae99ce4-cc44-40a4-8180-b08713668233")]
            public virtual Ranorex.Text NormalOutput
            {
                get
                {
                    return _normaloutputInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NormalOutput item info.
            /// </summary>
            [RepositoryItemInfo("3ae99ce4-cc44-40a4-8180-b08713668233")]
            public virtual RepoItemInfo NormalOutputInfo
            {
                get
                {
                    return _normaloutputInfo;
                }
            }

            /// <summary>
            /// The ClearButton item.
            /// </summary>
            [RepositoryItem("edb8d9b7-853e-4b36-b973-6b634c181e19")]
            public virtual Ranorex.Button ClearButton
            {
                get
                {
                    return _clearbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ClearButton item info.
            /// </summary>
            [RepositoryItemInfo("edb8d9b7-853e-4b36-b973-6b634c181e19")]
            public virtual RepoItemInfo ClearButtonInfo
            {
                get
                {
                    return _clearbuttonInfo;
                }
            }

            /// <summary>
            /// The SomeText item.
            /// </summary>
            [RepositoryItem("36d7a303-6702-41aa-bca7-da878644ff65")]
            public virtual Ranorex.Text SomeText
            {
                get
                {
                    return _sometextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SomeText item info.
            /// </summary>
            [RepositoryItemInfo("36d7a303-6702-41aa-bca7-da878644ff65")]
            public virtual RepoItemInfo SomeTextInfo
            {
                get
                {
                    return _sometextInfo;
                }
            }

            /// <summary>
            /// The Icon item.
            /// </summary>
            [RepositoryItem("12e21b71-7009-43ec-85d6-5caeb68ade14")]
            public virtual Ranorex.Text Icon
            {
                get
                {
                    return _iconInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Icon item info.
            /// </summary>
            [RepositoryItemInfo("12e21b71-7009-43ec-85d6-5caeb68ade14")]
            public virtual RepoItemInfo IconInfo
            {
                get
                {
                    return _iconInfo;
                }
            }

            /// <summary>
            /// The Programmer item.
            /// </summary>
            [RepositoryItem("ee916f84-b6af-4451-afe0-016fb874d28b")]
            public virtual Ranorex.ListItem Programmer
            {
                get
                {
                    return _programmerInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Programmer item info.
            /// </summary>
            [RepositoryItemInfo("ee916f84-b6af-4451-afe0-016fb874d28b")]
            public virtual RepoItemInfo ProgrammerInfo
            {
                get
                {
                    return _programmerInfo;
                }
            }

            /// <summary>
            /// The Header item.
            /// </summary>
            [RepositoryItem("82ce8e8d-9011-4985-a2af-8f2a50d4075f")]
            public virtual Ranorex.Text Header
            {
                get
                {
                    return _headerInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Header item info.
            /// </summary>
            [RepositoryItemInfo("82ce8e8d-9011-4985-a2af-8f2a50d4075f")]
            public virtual RepoItemInfo HeaderInfo
            {
                get
                {
                    return _headerInfo;
                }
            }

            /// <summary>
            /// The Maximize item.
            /// </summary>
            [RepositoryItem("79318610-2086-4409-a16f-2674ab0c704b")]
            public virtual Ranorex.Button Maximize
            {
                get
                {
                    return _maximizeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Maximize item info.
            /// </summary>
            [RepositoryItemInfo("79318610-2086-4409-a16f-2674ab0c704b")]
            public virtual RepoItemInfo MaximizeInfo
            {
                get
                {
                    return _maximizeInfo;
                }
            }

            /// <summary>
            /// The TogglePaneButton item.
            /// </summary>
            [RepositoryItem("882b82cd-d4ef-4cfa-b97e-74e9a96f3848")]
            public virtual Ranorex.Button TogglePaneButton
            {
                get
                {
                    return _togglepanebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The TogglePaneButton item info.
            /// </summary>
            [RepositoryItemInfo("882b82cd-d4ef-4cfa-b97e-74e9a96f3848")]
            public virtual RepoItemInfo TogglePaneButtonInfo
            {
                get
                {
                    return _togglepanebuttonInfo;
                }
            }

            /// <summary>
            /// The Standard item.
            /// </summary>
            [RepositoryItem("49315fdc-49f8-44fc-839a-f26f2a1115f8")]
            public virtual Ranorex.ListItem Standard
            {
                get
                {
                    return _standardInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Standard item info.
            /// </summary>
            [RepositoryItemInfo("49315fdc-49f8-44fc-839a-f26f2a1115f8")]
            public virtual RepoItemInfo StandardInfo
            {
                get
                {
                    return _standardInfo;
                }
            }

            /// <summary>
            /// The PlusButton item.
            /// </summary>
            [RepositoryItem("a9775261-69cd-4d1f-8bdd-1c00b6f0a2a1")]
            public virtual Ranorex.Button PlusButton
            {
                get
                {
                    return _plusbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PlusButton item info.
            /// </summary>
            [RepositoryItemInfo("a9775261-69cd-4d1f-8bdd-1c00b6f0a2a1")]
            public virtual RepoItemInfo PlusButtonInfo
            {
                get
                {
                    return _plusbuttonInfo;
                }
            }

            /// <summary>
            /// The NumberPad folder.
            /// </summary>
            [RepositoryFolder("122db3d7-0930-422e-8c15-af20a1d035dc")]
            public virtual PreEmpRepositoryFolders.NumberPadFolder NumberPad
            {
                get { return _numberpad; }
            }
        }

        /// <summary>
        /// The NumberPadFolder folder.
        /// </summary>
        [RepositoryFolder("122db3d7-0930-422e-8c15-af20a1d035dc")]
        public partial class NumberPadFolder : RepoGenBaseFolder
        {
            RepoItemInfo _num1buttonInfo;
            RepoItemInfo _num2buttonInfo;
            RepoItemInfo _num9buttonInfo;
            RepoItemInfo _num3buttonInfo;

            /// <summary>
            /// Creates a new NumberPad  folder.
            /// </summary>
            public NumberPadFolder(RepoGenBaseFolder parentFolder) :
                    base("NumberPad", "?/?/container[@automationid='NumberPad']", parentFolder, 30000, null, false, "122db3d7-0930-422e-8c15-af20a1d035dc", "")
            {
                _num1buttonInfo = new RepoItemInfo(this, "Num1Button", "button[@automationid='num1Button']", 30000, null, "51a54f78-1e4b-4540-9047-765ce7f9b68c");
                _num2buttonInfo = new RepoItemInfo(this, "Num2Button", "button[@automationid='num2Button']", 30000, null, "315d905f-8085-496e-8301-681809fad6dc");
                _num9buttonInfo = new RepoItemInfo(this, "Num9Button", "button[@automationid='num9Button']", 30000, null, "78a7d60e-adbf-40d7-9510-9ef34fc8a218");
                _num3buttonInfo = new RepoItemInfo(this, "Num3Button", "button[@automationid='num3Button']", 30000, null, "38a138b8-f205-4adb-8072-520752452bea");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("122db3d7-0930-422e-8c15-af20a1d035dc")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("122db3d7-0930-422e-8c15-af20a1d035dc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Num1Button item.
            /// </summary>
            [RepositoryItem("51a54f78-1e4b-4540-9047-765ce7f9b68c")]
            public virtual Ranorex.Button Num1Button
            {
                get
                {
                    return _num1buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num1Button item info.
            /// </summary>
            [RepositoryItemInfo("51a54f78-1e4b-4540-9047-765ce7f9b68c")]
            public virtual RepoItemInfo Num1ButtonInfo
            {
                get
                {
                    return _num1buttonInfo;
                }
            }

            /// <summary>
            /// The Num2Button item.
            /// </summary>
            [RepositoryItem("315d905f-8085-496e-8301-681809fad6dc")]
            public virtual Ranorex.Button Num2Button
            {
                get
                {
                    return _num2buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num2Button item info.
            /// </summary>
            [RepositoryItemInfo("315d905f-8085-496e-8301-681809fad6dc")]
            public virtual RepoItemInfo Num2ButtonInfo
            {
                get
                {
                    return _num2buttonInfo;
                }
            }

            /// <summary>
            /// The Num9Button item.
            /// </summary>
            [RepositoryItem("78a7d60e-adbf-40d7-9510-9ef34fc8a218")]
            public virtual Ranorex.Button Num9Button
            {
                get
                {
                    return _num9buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num9Button item info.
            /// </summary>
            [RepositoryItemInfo("78a7d60e-adbf-40d7-9510-9ef34fc8a218")]
            public virtual RepoItemInfo Num9ButtonInfo
            {
                get
                {
                    return _num9buttonInfo;
                }
            }

            /// <summary>
            /// The Num3Button item.
            /// </summary>
            [RepositoryItem("38a138b8-f205-4adb-8072-520752452bea")]
            public virtual Ranorex.Button Num3Button
            {
                get
                {
                    return _num3buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num3Button item info.
            /// </summary>
            [RepositoryItemInfo("38a138b8-f205-4adb-8072-520752452bea")]
            public virtual RepoItemInfo Num3ButtonInfo
            {
                get
                {
                    return _num3buttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
